# Generated by Django 6.1.1 on 2026-09-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rego', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Rego / plate')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, verbose_name='VIN')),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('fuel_card_number', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, choices=[('Unleaded 91', 'Unleaded 91'), ('Unleaded 95', 'Unleaded 95'), ('Unleaded 98', 'Unleaded 98'), ('Diesel', 'Diesel'), ('Premium diesel', 'Premium diesel'), ('LPG', 'LPG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('rego_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('service_interval_km', models.PositiveIntegerField(default=10000)),
                ('tyre_interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_row_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Refrigeration unit', 'Refrigeration unit'), ('Scheduled service', 'Scheduled service'), ('Tyre rotation', 'Tyre rotation'), ('Tyre replacement', 'Tyre replacement'), ('Brake service', 'Brake service'), ('Repair / parts', 'Repair / parts'), ('Registration', 'Registration'), ('Insurance', 'Insurance'), ('Fuel log', 'Fuel log')], max_length=32)),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_due', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='fleet_servi_vehicle_81a58c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Accident', 'Accident'), ('Breakdown', 'Breakdown'), ('Damage', 'Damage'), ('Other', 'Other')], max_length=16)),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major')], max_length=16)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved')], default='Open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='fleet_incid_vehicle_ac0d03_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='fleet_fuell_vehicle_1e45b5_idx')],
            },
        ),
    ]
