# Generated by Django 6.1.1 on 2026-09-29 00:18

from django.db import migrations, models
from django.utils import timezone


def mark_past_jobs_invoiced(apps, schema_editor):
    # Records that existed before statuses did are finished history; only
    # future-dated ones (bookings) keep the "Booked" default.
    ServiceRecord = apps.get_model("fleet", "ServiceRecord")
    ServiceRecord.objects.filter(date__lte=timezone.localdate()).update(status="Invoiced")


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('In service', 'In service'), ('Service completed', 'Service completed'), ('Waiting for invoice', 'Waiting for invoice'), ('Invoiced', 'Invoiced')], db_index=True, default='Booked', max_length=24),
        ),
        migrations.RunPython(mark_past_jobs_invoiced, migrations.RunPython.noop),
    ]
