# Generated by Django 6.1.1 on 2026-09-29 00:25

from django.db import migrations, models


def merge_completed(apps, schema_editor):
    ServiceRecord = apps.get_model("fleet", "ServiceRecord")
    ServiceRecord.objects.filter(status__in=["Service completed", "Waiting for invoice"]).update(
        status="Completed, awaiting invoice"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('In service', 'In service'), ('Completed, awaiting invoice', 'Completed, awaiting invoice'), ('Invoiced', 'Invoiced')], db_index=True, default='Booked', max_length=32),
        ),
        migrations.RunPython(merge_completed, migrations.RunPython.noop),
    ]
