# Generated by Django 6.1.1 on 2026-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_merge_completed_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
