# Generated by Django 6.1.1 on 2026-09-29 00:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def notes_to_log(apps, schema_editor):
    # Each incident's single free-text note becomes the first log entry,
    # dated when the incident was logged.
    Incident = apps.get_model("fleet", "Incident")
    IncidentUpdate = apps.get_model("fleet", "IncidentUpdate")
    for incident in Incident.objects.exclude(notes=""):
        IncidentUpdate.objects.create(incident=incident, text=incident.notes, created_at=incident.created_at)


def log_to_notes(apps, schema_editor):
    Incident = apps.get_model("fleet", "Incident")
    for incident in Incident.objects.all():
        incident.notes = "\n".join(u.text for u in incident.updates.order_by("created_at", "id"))
        incident.save(update_fields=["notes"])


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_incident_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fleet.incident')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(notes_to_log, log_to_notes),
        migrations.RemoveField(
            model_name='incident',
            name='notes',
        ),
    ]
