# Generated by Django 6.1.1 on 2026-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_incident_update_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='issues',
            field=models.TextField(blank=True),
        ),
    ]
