# Generated by Django 6.1.1 on 2026-09-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_service_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('Refrigeration unit', 'Refrigeration unit'), ('Scheduled service', 'Scheduled service'), ('Tyre rotation', 'Tyre rotation'), ('Tyre replacement', 'Tyre replacement'), ('Brake service', 'Brake service'), ('Repair / parts', 'Repair / parts'), ('Registration', 'Registration'), ('Insurance', 'Insurance'), ('Fuel log', 'Fuel log'), ('Van wash', 'Van wash')], max_length=32),
        ),
    ]
