# Generated by Django 6.1.1 on 2026-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_van_wash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='wash_needed',
            field=models.BooleanField(default=True),
        ),
    ]
