# Generated by Django 6.1.1 on 2026-09-30 03:17

from django.db import migrations, models


def label_imported(apps, schema_editor):
    """Rows from the first statement import were all fuel; the note says
    which kind."""
    FuelLog = apps.get_model("fleet", "FuelLog")
    imported = FuelLog.objects.filter(notes__contains="imported from fuel statement")
    imported.filter(notes__icontains="premium diesel").update(product="Premium diesel")
    imported.filter(product="").update(product="Diesel")


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_wash_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='product',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(label_imported, migrations.RunPython.noop),
    ]
