# Generated by Django 6.1.1 on 2026-09-30 05:53

import django.db.models.deletion
import fleet.models
from django.conf import settings
from django.db import migrations, models


def give_each_van_a_token(apps, schema_editor):
    Vehicle = apps.get_model("fleet", "Vehicle")
    for v in Vehicle.objects.all():
        v.report_token = fleet.models.new_report_token()
        v.save(update_fields=["report_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_fuellog_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel card'), ('maintenance', 'Maintenance')], max_length=20, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Existing vans each need their own token: add the column, fill it
        # per row, then make it unique.
        migrations.AddField(
            model_name='vehicle',
            name='report_token',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(give_each_van_a_token, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='report_token',
            field=models.CharField(default=fleet.models.new_report_token, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fleet.models.attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('Invoice', 'Invoice'), ('Quote', 'Quote'), ('Registration', 'Registration'), ('Insurance', 'Insurance'), ('Photo', 'Photo'), ('Other', 'Other')], default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fleet.incident')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fleet.servicerecord')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.driver'),
        ),
    ]
