# Generated by Django 6.1.1 on 2026-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_mechanics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Quote', 'Quote'), ('Registration', 'Registration'), ('Insurance', 'Insurance'), ('Photo', 'Photo'), ('Issue photo', 'Issue photo'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
