# Generated by Django 6.1.1 on 2026-10-05 22:38

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_issue_photo_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='drive_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to=fleet.models.attachment_path),
        ),
    ]
