# Generated by Django 6.1.1 on 2026-10-06 01:09

import django.db.models.deletion
import fleet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_drive_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TollStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('file', models.FileField(blank=True, upload_to=fleet.models.toll_statement_path)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TollTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=5)),
                ('tag_number', models.CharField(blank=True, max_length=20)),
                ('plate', models.CharField(blank=True, max_length=12)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('road', models.CharField(max_length=80)),
                ('detail', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_fee', models.BooleanField(default=False)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.tollstatement')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='fleet_tollt_vehicle_12e8d4_idx')],
            },
        ),
    ]
