# Generated by Django 6.1.1 on 2026-10-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_tolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollstatement',
            name='done',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
