# Generated by Django 6.1.1 on 2026-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_toll_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollstatement',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
