# Generated by Django 6.1.1 on 2026-10-09 00:03

import re
from datetime import date

from django.db import migrations, models


def tag_imported_lines(apps, schema_editor):
    """Lines imported from a statement say so in their note ("imported from fuel
    statement 08-10-2026"); give each its statement date."""
    FuelLog = apps.get_model("fleet", "FuelLog")
    pattern = re.compile(r"imported from fuel statement (\d{2})-(\d{2})-(\d{4})")
    for log in FuelLog.objects.filter(notes__contains="imported from fuel statement").iterator():
        m = pattern.search(log.notes)
        if m:
            FuelLog.objects.filter(pk=log.pk).update(statement=date(int(m.group(3)), int(m.group(2)), int(m.group(1))))


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_toll_pdf_in_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='statement',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(tag_imported_lines, migrations.RunPython.noop),
    ]
